PACKAGE_NAME="atl1c-ccr2004fix"
PACKAGE_VERSION="1.1"
BUILT_MODULE_NAME[0]="atl1c"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make -C src KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C src clean"
AUTOINSTALL="yes"
